[package]
name = "logging"
description = "The shared logging setup for The Hacker App services"
version = "0.1.0"
license = "MIT"
homepage = "https://github.com/TheHackerApp/logging"
repository = "https://github.com/TheHackerApp/logging.git"
edition = "2021"
publish = ["wafflehacks"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
