---
name: Build

on:  # yamllint disable-line rule:truthy
  - push

jobs:
  generate-matrix:
    name: Generate Build Matrix
    runs-on: ubuntu-22.04
    outputs:
      features: ${{ steps.generate-matrix.outputs.features }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python3 ./tools/features.py
        id: generate-matrix

  library:
    name: Library (${{ matrix.features }})
    runs-on: ubuntu-22.04
    needs: [generate-matrix]
    strategy:
      fail-fast: false
      matrix:
        features: ${{ fromJSON(needs.generate-matrix.outputs.features) }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release -F "${{ matrix.features }}"
